mod 'puppet/nginx'
mod 'puppetlabs/stdlib', '4.9.0'
mod 'puppetlabs/concat', '2.1.0'
mod 'puppetlabs/translate', '1.0.0'
#mod 'puppetlabs-apt', '6.0.0'
mod 'puppetlabs-apt', '2.1.1'
mod 'stahnma-epel', '1.1.1'
mod 'garethr-docker', '4.1.1'
#mod 'puppetlabs-docker', '3.5.0'
